---

home: "{{ lookup('env','HOME') }}"
i3wm_repo: "https://github.com/patkaehuaea/i3wm-config.git"
i3wm_dest: "{{ home }}/src/i3wm-config"
i3wm_config_dir: "{{ home }}/.config/i3"
i3wm_user: "{{ ansible_user_id }}"
i3wm_group: "users"

pacman:
  - 'alsa-utils' # Contains alsamixer and amixer utililities. Shell command and interface for audio settings.
  - 'i3-gaps' # i3-gaps – i3 with more features (forked from https://github.com/i3/i3)
  - 'maim' # Utility used by binary in i3wm to take screenshots.
  - 'otf-font-awesome' # OTF (OpenType) font package for font-awesome. Used initially for Awesome WM theme here: https://github.com/lcpz/awesome-copycats/tree/master/themes/vertex.
  - 'pamixer' # Wonderful CLI to configure pulseaudio settings. Useful since it doesn't allow volume > 100 by default.
  - 'papirus-icon-theme'
  - 'picom' # Picom is a standalone compositor for Xorg, suitable for use with window managers that do not provide compositing.
  - 'powerline-fonts'
  - 'pulseaudio-bluetooth' # Bluetooth support for PulseAudio
  - 'ranger' # A VIM-inspired filemanager for the console https://ranger.github.io/
  - 'redshift' # Redshift adjusts the color temperature of your screen according to your surroundings. This may help your eyes hurt less if you are working in front of the screen at night.
  - 'ttf-font-awesome' # TTF (TrueType) font package for font-awesome.  Used initially for Awesome WM theme here: https://github.com/lcpz/awesome-copycats/tree/master/themes/vertex.
  - 'ttf-hack' # TTF (TrueType) font package for hack font. Needed to display certain unicode characters in vim.
  - 'wavemon' # Terminal based wifi utility.
  - 'wmctrl' # Utility to kill plasma at i3 startup
  - 'xclip' # Command line interface to the X11 clipboard. Used to help capture screenshots via snap, maim, and AwesomeWM.
  - 'xfce4-pulseaudio-plugin' # Panel applet which has support for keyboard volume control and notifications.
  - 'xorg-xdpyinfo' # Verify that the X Server has properly detected the physical dimensions of your monitor e.g. xdpyinfo | grep -B 2 resolution
yay:
  - 'polybar' # A fast and easy-to-use status bar
  - 'rofi-git' # system menu
  - 'system-san-francisco-font-git' # Another font for polybar
  - 'ttf-material-design-icons' # Icon font for polybar, etc.
  - 'ttf-iosevka' # Font set for polybar
  - 'ttf-nerd-fonts-hack-complete-git' # Polybar icons won't show without these fonts installed
  - 'virtualbox-ext-oracle' # resize window won't work without this
