---

- hosts: localhost

  vars:

    dotfiles_repo: "https://github.com/patkaehuaea/dotfiles"
    dotfiles_repo_local_destination: "~/src/dotfiles"
    dotfiles_home: "~"
    dotfiles_files:
        - .config/alacritty
        - .config/picom.conf
        - .config/polybar
        - .config/rofi
        - .gitconfig
        - .gitignore
        - .shellaliases
        - .shellfn
        - .shellpaths
        - .shellvars
        - .tmux.conf
        - .todo.cfg
        - .vimrc
        - .xinitrc
        - .xprofile
        - .Xresources
        - .Xresources.d
        - .xsession
        - .zlogin
        - .zshenv
        - .zshrc

  roles:
    - kewlfft.aur # Doesn't actually do anything. Just makes namespace available for tasks.

  tasks:

    - include_role:
        name: common

    - include_role:
        name: geerlingguy.dotfiles # The .config directory must exist or role fails for files in ~/.config.

    - include_role:
        name: awesomewm

    - include_role:
        name: xmonad

    # Do last since this will kill the run and
    # boot user to sddm login.
    - name: Make sure the display manager is running
      systemd:
        enabled: yes
        state: started
        name: sddm.service
      become: yes
