---

- hosts: localhost

  vars:

    pacman:
      - 'aws-cli'
      - 'bc' # Arbitrary precision calculator language required by bonsai.sh.
      - 'blueman' # Blueman is a full featured Bluetooth manager written in GTK. Used to enable bluetooth widget in AwesomeWM.
      - 'bluez'
      - 'bluez-utils'
      - 'cmatrix' # Why wouldn't I want matrix in a terminal? :)
      - 'containerd' # Docker dependency
      - 'curl'
      - 'device-mapper' # Docker dependency
      - 'dnsutils' #Includes utilities like 'dig' and 'host'
      - 'docker'
      - 'git'
      - 'gtk-engine-murrine' # Murrine GTK+ Cairo Engine 
      - 'gtop' # Sweet implementation of htop in go. Did I saw sweet?
      - 'go' # Core compiler and tools for the Go programming language
      - 'gwenview' # Gwenview is a fast and easy to use image viewer by KDE, ideal for browsing and displaying a collection of images.
      - 'htop' # An interactive process viewer for Unix systems.
      - 'hwinfo'
      - 'kubectl' # CLI for kubernetes API
      - 'kde-cli-tools' # Installs kwriteconfig5 and kreadconfig5 for updating KDE configs e.g. ~/.config/kwinrulesrc
      - 'ktorrent' # Download and manage bittorrents.
      - 'kvantum-qt5' # Kvantum engine and theme manager for additional theme customizations.
      #  - 'plasma5-applets-active-window-control' # Enable window decorations panel in system settings.
      - 'lm_sensors hddtemp' # Find hdd temperatures at login.
      - 'libappindicator-gtk3' # Resolves 'ValueError: Namespace AppIndicator3 not available after installing blueman.
      - 'lsof'
      - 'man'
      - 'minikube' # Run a local kubernetes cluster.
      - 'nmap'
      - 'openssh'
      - 'packer'
      - 'procps-ng' # Command line and full screen utilities for browsing procfs, a "pseudo" file system dynamically generated by the kernel to provide information about the status of entries in its process table.
      - 'python-pip'
      - 'ranger' # A VIM-inspired filemanager for the console https://ranger.github.io/
      - 'samba' # Good 'ol SMB ; used to transfer backups from homeassistant
      - 'signal-desktop' # Secure, cross-platform messaging app
      - 'spectacle'
      - 'steam' # Play games with Steam for Linux.
      - 'terminus-font-otb' # Play games with Steam for Linux.
      - 'tmux' # A terminal multiplexer: tmux enables a number of terminals to be created, accessed, and controlled from a single screen.
      - 'tree'
      - 'virtualbox' # Use virtualbox-host-modules-arch.
      - 'wget'
      - 'yay' # Arch AUR helper.
      - 'virtualbox-host-modules-arch' # VirtualBox host modules needed for shared clipboard, bridged network, etc.

    yay:
      - 'indicator-sound-switcher'
      - 'nordvpn-bin'
      # TODO: Fix proton install with yay
      #      - 'proton' # Compatibility tool for Steam Play based on Wine and additional components.
      - 'realvnc-vnc-viewer'
      - 'slack-desktop'
      - 'terminus-font'
      - 'todotxt' # Command line todo list.

  roles:
    - kewlfft.aur

  tasks:

    - include_role:
        name: common
        name: awesomewm
        name: i3wm

    - name: Run the equivalent of "pacman -Sy" before installs
      pacman:
        update_cache: yes
      become: yes

    - name: Install applications with pacman
      pacman:
       name: '{{ item }}'
       state: present
      loop: "{{ pacman }}"
      become: yes

    - name: use yay to install applications from the AUR
      aur:
        name: '{{ item }}'
      loop: '{{ yay }}'

    - name: Make sure bluetooth is enabled and running
      systemd:
        enabled: yes
        state: started
        name: bluetooth.service

    - name: Enable and start NetworkManager
      systemd:
        enabled: yes
        state: started
        name: NetworkManager

    - name: Make sure docker daemon is enabled and running
      systemd:
        enabled: yes
        state: started
        name: docker.service

    # Need in order to use docker and mount USB
    # devices in VirtualBox.
    - name: adding current user to docker and vboxusers groups
      user:
        name: "{{ ansible_user_id }}"
        groups: docker,vboxusers
        append: yes

    - name: Start and enable nordvpn service
      systemd:
        enabled: yes
        state: started
        name: nordvpnd.service
      become: yes
