---
- hosts: all

  tasks:

      - name: Include all .json and .jsn files in group_vars and all nested directories (2.3)
        include_vars:
          dir: group_vars

      - include_tasks: tasks/directories.yml

      - include_tasks: tasks/packages.yml

      - include_tasks: tasks/dotfiles.yml

      - include_tasks: tasks/osx.yml
