---

- hosts: all

  vars:

    home: "{{ lookup('env','HOME') }}"

    directories:
      - "{{ home }}/.aws"
      - "{{ home }}/.azure"
      - "{{ home }}/.chef"
      - "{{ home }}/.ssh"
      - "{{ home }}/src"

  tasks:

      - name: Set OS distribution dependent variables
        include_vars: os_{{ ansible_facts['os_family'] }}.yml

      - name: Create configuration and source directories
        file: path={{ item }} state=directory
        with_items:
          - "{{ directories }}"

      - include_tasks: tasks/os_{{ ansible_facts['os_family'] }}.yml

      - pip:
          executable: pip3
          name: powerline-status
        become: yes

      - pip:
          executable: pip3
          name: powerline-gitstatus
        become: yes

      - name: Download and unarchive go binaries
        unarchive:
          src: '{{ go_src }}'
          dest: /usr/local/
          remote_src: yes
        become: yes

  roles:

    - role: patkaehuaea.ansible_role_dotfiles
      become: yes
