---
version: "3"

vars:
  PROJECT_DIR:
    sh: "git rev-parse --show-toplevel"
  ANSIBLE_PLAYBOOK_DIR: "{{.PROJECT_DIR}}/playbooks"
  ANSIBLE_INVENTORY_DIR: "{{.PROJECT_DIR}}/inventory"

env:
  ANSIBLE_CONFIG: "{{.PROJECT_DIR}}/ansible.cfg"

dotenv: [".config.env"]

tasks:

  default:
    cmds:
      - task: init
      - task: osx
      - task: install
      - task: dotfiles

  init:
    desc: Install Ansible and dependencies.
    cmds:
      - brew install {{.DEPS}} {{.CLI_ARGS}}
      - ansible-galaxy install -r {{.PROJECT_DIR}}/requirements.yml --roles-path ~/.ansible/roles --force
    preconditions:
      - sh: command -v brew
        msg: |
          Homebrew is not installed. Using MacOS, Linux or WSL?
          Head over to https://brew.sh to get up and running.
    vars:
      DEPS: >-
        ansible
        go-task/tap/go-task

  osx:
    desc: Configure OSX defaults.
    cmds:
      - ansible-playbook -i {{.ANSIBLE_INVENTORY_DIR}}/hosts {{.ANSIBLE_PLAYBOOK_DIR}}/osx-defaults.yml

  install:
    desc: Install packages with Ansible.
    cmds:
      - ansible-playbook -i {{.ANSIBLE_INVENTORY_DIR}}/hosts {{.ANSIBLE_PLAYBOOK_DIR}}/osx-install.yml

  dotfiles:
    desc: Clone then symlink dotfiles.
    cmds:
      - ansible-playbook -i {{.ANSIBLE_INVENTORY_DIR}}/hosts {{.ANSIBLE_PLAYBOOK_DIR}}/osx-dotfiles.yml
