---
version: "3"

vars:
  PROJECT_DIR:
    sh: "git rev-parse --show-toplevel"
  ANSIBLE_PLAYBOOK_DIR: "{{.PROJECT_DIR}}/playbooks"
  ANSIBLE_INVENTORY_DIR: "{{.PROJECT_DIR}}/inventory"

env:
  ANSIBLE_CONFIG: "{{.PROJECT_DIR}}/ansible.cfg"

dotenv: [".config.env"]

includes:
  ansible: .taskfiles/AnsibleTasks.yml
  precommit: .taskfiles/PrecommitTasks.yml

tasks:

  default:
    cmds:
      - task: init
      - task: ansible:init
      - task: precommit:init
      - task: ansible:run

  init:
    desc: Install Ansible and dependencies.
    cmds:
      - brew install {{.DEPS}} {{.CLI_ARGS}}
    preconditions:
      - sh: command -v brew
        msg: |
          Homebrew is not installed. Using MacOS, Linux or WSL?
          Head over to https://brew.sh to get up and running.
    vars:
      DEPS: >-
        ansible
        go-task/tap/go-task
