---

home: "{{ lookup('env','HOME') }}"
xmonad_repo: "https://github.com/patkaehuaea/xmonad-config.git"
xmonad_dest: "{{ home }}/src/xmonad-config"
xmonad_config_dir: "{{ home }}/.xmonad"

xmonad_wallpapers_repo: "https://gitlab.com/patkaehuaea/wallpapers.git"
xmonad_wallpapers_dest: "{{ home }}/src/wallpapers"

xmonad_pacman:
  - 'picom' # Picom is a standalone compositor for Xorg, suitable for use with window managers that do not provide compositing.
  #  - 'powerline-fonts'
  - 'pulseaudio-bluetooth' # Bluetooth support for PulseAudio
  - 'ranger' # A VIM-inspired filemanager for the console https://ranger.github.io/
  - 'redshift' # Redshift adjusts the color temperature of your screen according to your surroundings. This may help your eyes hurt less if you are working in front of the screen at night.
  - 'xmonad'
  - 'xmonad-contrib'
  - 'xorg-xdpyinfo' # Verify that the X Server has properly detected the physical dimensions of your monitor e.g. xdpyinfo | grep -B 2 resolution
  - 'feh' # utility to set wallpaper background

xmonad_yay:
  - 'rofi-git' # system menu
  - 'otf-san-francisco' # System font used in OSX.
  - 'ttf-material-design-icons' # Icon font used for glyphs.
  - 'ttf-iosevka' # Another font alternative.
  - 'polybar' # Used as replacement for xmobar.
  - 'powerline-fonts-git' # May conflict with other fonts and need manual intervention.
  - 'ttf-nerd-fonts-hack-complete-git' # Collection of fonts used for glyph support.
