---
- name: install skhd
  homebrew:
    name: koekeishiya/formulae/skhd
    state: present
    update_homebrew: yes

- name: install
  homebrew:
    name: yabai
    state: present
    update_homebrew: yes

- name: start yabai
  command: brew services restart yabai

- name: start skhd
  command: brew services restart koekeishiya/formulae/skhd
