---
        - name: Run the equivalent of "pacman -Sy" before installs
          pacman:
            update_cache: yes
          become: yes

        - name: Install applications with pacman
          pacman:
            name: '{{ item }}'
            state: present
          loop: "{{ pacman }}"
          become: yes

        - name: Make sure a service is running
          systemd:
            enabled: yes
            state: started
            name: bluetooth.service

        - name: Clone yay repository
          git:
            repo: https://aur.archlinux.org/yay.git
            dest: ~/src/yay

        - name: Build yay with makepkg
          shell:
            cmd: makepkg -si
            chdir: ~/src/yay
            # Will not run if /usr/bin/yay exists.
            creates: /usr/bin/yay


