---

  - name: Install applications with homebrew
    homebrew:
      name: '{{ item }}'
      state: present
      update_homebrew: yes
    loop: "{{ brew }}"

  - name: Install fonts with homebrew tap
    # Need to restart iTerm for 'Hack Nerd Font' to be available.
    homebrew_tap:
      name: homebrew/cask-fonts

  - name: Install applications with homebrew cask
    homebrew_cask:
      name: '{{ item }}'
      state: present
    loop: "{{ cask }}"

     # Requests module used by the iterm2 integration
     # as sourced by ~/.profile.
   - pip:
       name: requests
       extra_args: --user

  - name: Automatically quit printer app once the print jobs complete
    shell: defaults write com.apple.print.PrintingPrefs "Quit When Finished" -bool true

  - name: Disable smart quotes as they’re annoying when typing code
    shell: defaults write NSGlobalDomain NSAutomaticQuoteSubstitutionEnabled -bool false

  - name: Disable smart dashes as they’re annoying when typing code
    shell: defaults write NSGlobalDomain NSAutomaticDashSubstitutionEnabled -bool false

  - name: Disable the “Are you sure you want to open this application?” dialog
    shell: defaults write com.apple.LaunchServices LSQuarantine -bool false

  - name: Disable the crash reporter
    shell: defaults write com.apple.CrashReporter DialogType -string "none"

  - name: Show ~/Library
    shell: chflags nohidden ~/Library

  - name: Show Drives on the Desktop
    shell: defaults write com.apple.finder ShowHardDrivesOnDesktop -bool true

  - name: Show External Drives on the Desktop
    shell: defaults write com.apple.finder ShowExternalHardDrivesOnDesktop -bool true

  - name: Show Removable Media on the Desktop
    shell: defaults write com.apple.finder ShowRemovableMediaOnDesktop -bool true

  - name: Show Mounted Servers on the Desktop
    shell: defaults write com.apple.finder ShowMountedServersOnDesktop -bool true

  - name: Show Hidden Files
    shell: defaults write com.apple.finder AppleShowAllFiles -bool true

  - name: Kill finder to apply changes
    shell: killall -HUP Finder
