---

- name: Run the equivalent of "pacman -Sy" before installs
  pacman:
    update_cache: yes
  become: yes

- name: Install applications with pacman
  pacman:
    name: '{{ item }}'
    state: present
  loop: "{{ pacman }}"
  become: yes

- name: use yay to install applications from the AUR
  aur:
    use: yay
    name: '{{ item }}'
    state: present
  loop: "{{ yay }}"

- name: clone awesomewm-config repository
  git:
    repo: '{{ awesomewm_repo }}'
    dest: '{{ awesomewm_dest }}'

- name: create ~/.config/awesome symlink
  file:
    src: '{{ awesomewm_dest }}' 
    dest: '{{ awesomewm_config_dir }}'
    owner: '{{ ansible_user_id }}'
    group:  '{{ ansible_user_gid }}'
    state: link
