---

- name: Run the equivalent of "pacman -Sy" before installs
  pacman:
    update_cache: yes
  become: yes

- name: Install applications with pacman
  pacman:
    name: '{{ item }}'
    state: present
  loop: "{{ pacman }}"
  become: yes

- name: use yay to install applications from the AUR
  aur:
    use: yay
    name: '{{ item }}'
    #state: present
  loop: "{{ yay }}"

- name: clone i3wm-config repository
  git:
    repo: '{{ i3wm_repo }}'
    dest: '{{ i3wm_dest }}'

- name: create ~/.config/i3 symlink
  file:
    src: '{{ i3wm_dest }}' 
    dest: '{{ i3wm_config_dir }}'
    owner: '{{ i3wm_user }}'
    group:  '{{ i3wm_group }}'
    state: link
