---

- name: Set OS distribution dependent variables
  include_vars: os_{{ ansible_facts['os_family'] }}.yml

- name: Create configuration and source directories
  file: path={{ item }} state=directory
  with_items:
    - "{{ directories }}"

- name: Include OS distribution dependent tasks
  include_tasks: tasks/os_{{ ansible_facts['os_family'] }}.yml

- name: Create vim autoload directory for plug.vim
  file:
    path: ~/.vim/autoload
    state: directory

- name: Download Plug.vim from github
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: ~/.vim/autoload/plug.vim

- name: Use vim-plug to install plugins on the command line
  shell: vim -es -u ~/.vimrc -i NONE -c "PlugInstall" -c "qa"
  # Even when this works, the command still exits 1. 
  # ref: https://github.com/junegunn/vim-plug/wiki/tips#install-plugins-on-the-command-line
  ignore_errors: true

- name: Clone oh-my-zsh git repository
  git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: "{{ zsh_ohmyzsh }}"
    # If clone not set to 'yes' then ansible will do nothing on a new install.
    # Set update to 'no' so that when there are changes, themes, etc. we won't fail clone.
    clone: yes
    update: no

- name: Clone powerlevel9k oh-my-zsh theme
  git:
    repo: https://github.com/bhilburn/powerlevel9k.git
    dest: "{{ zsh_custom }}/themes/powerlevel9k"
    bare: yes
    force: yes

- name: Create symlink for powerlevel9k oh-my-zsh theme
  file:
    src: "{{ zsh_custom }}/themes/powerlevel9k/powerlevel9k.zsh-theme"
    dest: "{{ zsh_custom }}/themes/powerlevel9k.zsh-theme"
    state: link
    force: yes

- name: Clone spaceship-prompt oh-my-zsh theme
  git:
    repo: https://github.com/denysdovhan/spaceship-prompt.git
    dest: "{{ zsh_custom }}/themes/spaceship-prompt"
    clone: yes

- name: Create symlink for spaceship-prompt oh-my-zsh theme
  file:
    src: "{{ zsh_custom }}/themes/spaceship-prompt/spaceship.zsh-theme"
    dest: "{{ zsh_custom }}/themes/spaceship.zsh-theme"
    state: link
    force: yes

- name: Clone zsh-autosuggestions plugin
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: "{{ zsh_custom }}/plugins/zsh-autosuggestions"
    clone: yes
