---

- name: Clone dotfiles repository
  git:
    repo: "{{ dotfiles_repo }}"
    dest: "{{ dotfiles_dest }}"

- name: Create configuration and source directories
  file: path={{ item }} state=directory
  with_items:
    - "{{ directories }}"

- name: Download and unarchive go binaries
  unarchive:
    src: 'https://dl.google.com/go/go1.13.8.linux-amd64.tar.gz'
    dest: /usr/local/
    remote_src: yes
  become: yes
  when: ansible_facts['os_family'] == "Archlinux"

- include_tasks: go.yml
- include_tasks: vim.yml
- include_tasks: zsh.yml
