---

- name: Run the equivalent of "pacman -Sy" before installs
  pacman:
    update_cache: yes
  become: yes

- name: Install applications with pacman
  pacman:
   name: '{{ item }}'
   state: present
  loop: "{{ pacman }}"
  become: yes

- name: use yay to install applications from the AUR
  aur:
    name: '{{ item }}'
  loop: '{{ yay }}'

- name: Make sure bluetooth is enabled and running
  systemd:
    enabled: yes
    state: started
    name: bluetooth.service
  become: yes

- name: Enable and start NetworkManager
  systemd:
    enabled: yes
    state: started
    name: NetworkManager
  become: yes

- name: Make sure docker daemon is enabled and running
  systemd:
    enabled: yes
    state: started
    name: docker.service
  become: yes

# Need in order to use docker and mount USB
# devices in VirtualBox.
- name: adding current user to docker and vboxusers groups
  user:
    name: "{{ ansible_user_id }}"
    groups: docker,vboxusers
    append: yes
  become: yes

- name: Start and enable nordvpn service
  systemd:
    enabled: yes
    state: started
    name: nordvpnd.service
  become: yes
