---

- name: Install vim with pacman
  pacman:
    name: 'vim'
    state: present
  become: yes
  when: ansible_facts['os_family'] == "Archlinux"

- name: Create vim autoload directory for plug.vim
  file:
    path: ~/.vim/autoload
    state: directory

- name: Download Plug.vim from github
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: ~/.vim/autoload/plug.vim

- name: Use vim-plug to install plugins on the command line
  shell: vim -es -u ~/.vimrc -i NONE -c "PlugInstall" -c "qa"
  # Even when this works, the command still exits 1. 
  # ref: https://github.com/junegunn/vim-plug/wiki/tips#install-plugins-on-the-command-line
  ignore_errors: true

- pip:
    executable: pip3
    name: powerline-status
  become: yes

- pip:
    executable: pip3
    name: powerline-gitstatus
  become: yes
