---

- name: Install zsh with pacman
  pacman:
    name: 'zsh'
    state: present
  become: yes
  when: ansible_facts['os_family'] == "Archlinux"

- name: Clone oh-my-zsh git repository
  git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: "{{ zsh_ohmyzsh }}"
    # If clone not set to 'yes' then ansible will do nothing on a new install.
    # Set update to 'no' so that when there are changes, themes, etc. we won't fail clone.
    clone: yes
    update: no

- name: Clone powerlevel9k oh-my-zsh theme
  git:
    repo: https://github.com/bhilburn/powerlevel9k.git
    dest: "{{ zsh_custom }}/themes/powerlevel9k"
    bare: yes
    force: yes

- name: Create symlink for powerlevel9k oh-my-zsh theme
  file:
    src: "{{ zsh_custom }}/themes/powerlevel9k/powerlevel9k.zsh-theme"
    dest: "{{ zsh_custom }}/themes/powerlevel9k.zsh-theme"
    state: link
    force: yes

- name: Clone spaceship-prompt oh-my-zsh theme
  git:
    repo: https://github.com/denysdovhan/spaceship-prompt.git
    dest: "{{ zsh_custom }}/themes/spaceship-prompt"
    clone: yes

- name: Create symlink for spaceship-prompt oh-my-zsh theme
  file:
    src: "{{ zsh_custom }}/themes/spaceship-prompt/spaceship.zsh-theme"
    dest: "{{ zsh_custom }}/themes/spaceship.zsh-theme"
    state: link
    force: yes
