---
home: "{{ lookup('env','HOME') }}"
directories:
  - "{{ home }}/.aws"
  - "{{ home }}/.azure"
  # Needed for any dotfile linking for application configs under ~/.config. Link will fail if ~/.config does not exist.
  - "{{ home }}/.config"
  - "{{ home }}/.ssh"
  - "{{ home }}/src"
dotfiles_repo: "https://github.com/patkaehuaea/dotfiles.git"
dotfiles_dest: "{{ home }}/src/dotfiles"
dotfiles_user_home: "{{ home }}"
zsh_ohmyzsh: "{{ home }}/.oh-my-zsh"
zsh_config: "{{ home }}/.zshrc"
zsh_custom: "{{ zsh_ohmyzsh }}/custom"
