---

pacman:
  - 'alacritty'
  - 'aws-cli'
  - 'bc' # Arbitrary precision calculator language required by bonsai.sh.
  - 'base-devel' # Needed to compile packages. Will see errors in yay if not installed.
  - 'blueman' # Blueman is a full featured Bluetooth manager written in GTK. Used to enable bluetooth widget in AwesomeWM.
  - 'bluez'
  - 'bluez-utils'
  - 'cmatrix' # Why wouldn't I want matrix in a terminal? :)
  - 'containerd' # Docker dependency
  - 'curl'
  - 'device-mapper' # Docker dependency
  - 'discord' # Yet another chat client
  - 'dnsutils' #Includes utilities like 'dig' and 'host'
  - 'dmenu' # dynamic menu for X
  - 'docker'
  - 'firefox' # mozilla firefox web browser
  - 'git'
  - 'gtk-engine-murrine' # Murrine GTK+ Cairo Engine 
  - 'gtop' # Sweet implementation of htop in go. Did I saw sweet?
  - 'go' # Core compiler and tools for the Go programming language
  - 'gwenview' # Gwenview is a fast and easy to use image viewer by KDE, ideal for browsing and displaying a collection of images.
  - 'htop' # An interactive process viewer for Unix systems.
  - 'hwinfo'
  - 'kubectl' # CLI for kubernetes API
  - 'libappindicator-gtk3' # Resolves 'ValueError: Namespace AppIndicator3 not available after installing blueman.
  - 'lsof'
  - 'make'
  - 'man'
  - 'minikube' # Run a local kubernetes cluster.
  - 'neofetch' # Display system information in terminal.
  - 'networkmanager' #  Daemon and CLI (nmcli) for managing network interfaces.
  - 'network-manager-applet' # Handy system tray applet for managing network connections.
  - 'nmap'
  - 'openssh'
  - 'packer'
  - 'pavucontrol' # Simple GTK volume control tool ("mixer") for PulseAudio.
  - 'procps-ng' # Command line and full screen utilities for browsing procfs, a "pseudo" file system dynamically generated by the kernel to provide information about the status of entries in its process table.
  - 'python-pip'
  - 'ranger' # A VIM-inspired filemanager for the console https://ranger.github.io/
  - 'samba' # Good 'ol SMB ; used to transfer backups from homeassistant
  - 'sddm' # Simple Desktop Display Manager - login GUI.
  - 'spectacle'
  - 'terminus-font-otb' # Play games with Steam for Linux.
  - 'tmux' # A terminal multiplexer: tmux enables a number of terminals to be created, accessed, and controlled from a single screen.
  - 'tree'
  - 'virtualbox' # Use virtualbox-host-modules-arch.
  - 'wget'
  - 'xdotool' # Command-line X11 automation tool
  - 'xorg-xrdb' # Provides 'xrdb' utility used in .Xresources file.
  - 'xmonad'
  - 'xmonad-contrib'
  # Conflicts with virtualbox-host-modules-dkms ... see if works then delete.
  #- 'virtualbox-host-modules-arch' # VirtualBox host modules needed for shared clipboard, bridged network, etc.

yay:
  - 'autojump-git' # Fast way to navigate filesystem.
  - 'google-chrome'
  - 'python-pywal' # Color theme generator.
  - 'teams'
  - 'toilet' # Used to process text displayed in terminal.
  - 'nordvpn-bin'
  - 'nerd-fonts-jetbrains-mono'
  - 'realvnc-vnc-viewer'
  - 'slack-desktop'
  - 'spotify' # Music client
  - 'terminus-font'
  - 'todotxt' # Command line todo list.
