---

- hosts: localhost

  tasks:
    - osx_defaults:
        domain: com.apple.Safari
        key: IncludeInternalDebugMenu
        type: bool
        value: true

    - name: Automatically quit printer app once the print jobs complete
      shell: defaults write com.apple.print.PrintingPrefs "Quit When Finished" -bool true

    - name: Disable smart quotes as they're annoying when typing code
      shell: defaults write NSGlobalDomain NSAutomaticQuoteSubstitutionEnabled -bool false

    - name: Disable smart dashes as they're annoying when typing code
      shell: defaults write NSGlobalDomain NSAutomaticDashSubstitutionEnabled -bool false

    - name: Disable the "Are you sure you want to open this application?" dialog
      shell: defaults write com.apple.LaunchServices LSQuarantine -bool false

    - name: Disable the crash reporter
      shell: defaults write com.apple.CrashReporter DialogType -string "none"

    - name: Show ~/Library
      shell: chflags nohidden ~/Library

    - name: Show Drives on the Desktop
      shell: defaults write com.apple.finder ShowHardDrivesOnDesktop -bool true

    - name: Show External Drives on the Desktop
      shell: defaults write com.apple.finder ShowExternalHardDrivesOnDesktop -bool true

    - name: Show Removable Media on the Desktop
      shell: defaults write com.apple.finder ShowRemovableMediaOnDesktop -bool true

    - name: Show Mounted Servers on the Desktop
      shell: defaults write com.apple.finder ShowMountedServersOnDesktop -bool true

    - name: Don't automatically rearrange Spaces based on most recent use
      shell: defaults write com.apple.dock mru-spaces -bool false
