---

- hosts: localhost

  vars:

    brew:
      - 'age'
      - 'azure-cli'
      - 'curl'
      - 'direnv'
      - 'dep'
      - 'fish'                    # shell
      - 'fisher'                  # plugin manager for fish shell
      - 'git'
      - 'go'
      - 'gnupg'
      - 'htop'
      - 'jq'
      - 'neofetch'
      - 'pre-commit'
      - 'prettier'
      - 'pyenv'
      - 'sops'
      - 'starship'                # shell prompt
      - 'stern'
      - 'terraform'
      - 'tflint'
      - 'todo-txt'
      - 'tree'
      - 'vim'
      - 'wget'
      - 'yamllint'
      - 'yq'

    cask:
      - 'docker'
      - 'font-hack-nerd-font'
      - 'kitty'
      - 'macdown'
      - 'microsoft-teams'
      - 'slack'
      - 'spaceman'                # view Mission Control spaces in menu bar
      - 'visual-studio-code'

  tasks:

    - name: Update homebrew and upgrade all packages
      community.general.homebrew:
        upgrade_all: true

    - name: Install applications with homebrew
      homebrew:
        name: '{{ item }}'
        state: present
        update_homebrew: true
      loop: "{{ brew }}"

    - name: Install fonts with homebrew tap
      # Need to restart iTerm for 'Hack Nerd Font' to be available.
      homebrew_tap:
        name: homebrew/cask-fonts

    - name: Install applications with homebrew cask
      community.general.homebrew_cask:
        name: '{{ item }}'
        state: present
      loop: "{{ cask }}"

    # Homebrew executable path is different on x86 versus Apple silicon.
    - name: Use vim-plug to install plugins on the command line
      ansible.builtin.shell: vim -es -u ~/.vimrc -i NONE -c "PlugInstall" -c "qa"
      args:
        executable: /opt/homebrew/bin/fish
      # Even when this works, the command still exits 1.
      # ref: https://github.com/junegunn/vim-plug/wiki/tips#install-plugins-on-the-command-line
      ignore_errors: true

    # Different brew install directories for Intal vs. Apple Silicon Macs
    - name: Install jethrokuan/z plugin
      ansible.builtin.shell: fisher install jethrokuan/z
      args:
        executable: /opt/homebrew/bin/fish
      when: ansible_architecture != "x86_64"

    - name: Install jethrokuan/z plugin
      ansible.builtin.shell: fisher install jethrokuan/z
      args:
        executable: /usr/local/bin/fish
      when: ansible_architecture == "x86_64"
